apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "@project.artifactId@"
roleRef:
  # Add the edit role to the service account
  kind: "Role"
  name: "edit"
subjects:
  - kind: "ServiceAccount"
    name: "@project.artifactId@"
